

import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { Container, Card, Text, Link, Input, Button, css, Col, Row } from "@nextui-org/react";


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>NextUI | Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app and using NextUI as a react UI library"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container
                as="main"
                display="flex"
                direction="column"
                justify="center"
                alignItems="center"
                style={{
                    height: '100vh',
                    background: '45deg, $blue600 -20%, $pink600 50%'


                }}
            >
                


            </Container>
        </div >
    );
}
