

import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { Container, Card, Text, Link, Input, Button, css, Col, Row } from "@nextui-org/react";


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>NextUI | Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app and using NextUI as a react UI library"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container
                as="main"
                display="flex"
                direction="column"
                justify="center"
                alignItems="center"
                style={{
                    height: '100vh',
                    background: '45deg, $blue600 -20%, $pink600 50%'


                }}
            >
                <Card css={{ width: '350px', height: '400px', pt: '30px' }} shadow>
                    <Card.Header css={{ p: '5px 20px' }}>

                        <Text h2 color="white">
                            Your checklist
                        </Text>

                    </Card.Header>
                    <Card.Body css={{ display: 'flex', alignItems: 'center', justifyContent: "end", gap: '40px' }}>
                        <Input
                            bordered
                            labelPlaceholder="Email"
                            width='100%'
                        />
                        <Input
                            bordered
                            labelPlaceholder="Password"
                            width='100%'
                            type={'password'} />
                        <Container css={{ display: 'flex', justifyContent: 'space-between', p: 0, }}>
                            <Button auto flat color="gradient" css={{ width: '40%' }} >
                                Sign up
                            </Button>
                            <Button auto css={{ width: '40%' }}>
                                Sign in
                            </Button>
                        </Container>
                    </Card.Body>
                    <Card.Footer>
                        <Link
                            color="primary"
                            target="_blank"
                            href="https://github.com/nextui-org/nextui"
                        >
                            Visit source code on GitHub.
                        </Link>
                    </Card.Footer>
                </Card>


            </Container>
        </div >
    );
}
