import Head from 'next/head';
import { Container, Text } from "@nextui-org/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextUI | Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Container

        // as="main"
        // display="flex"
        // direction="column"
        // justify="center"
        // alignItems="center"
        className='select-none mb-10'

      >






        
          <Container className='p-[18px] '>
            <Text className='text-green-300 hover:text-green-400 cursor-pointer p-[20px] font-bold' size={60}>🔥 Hello 🔥</Text>
          </Container>
          



      </Container>

    </div >
  );
}
